DROP DATABASE IF EXISTS veronicasoptica;
CREATE DATABASE veronicasoptica;
USE veronicasoptica;
CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_PROVEEDOR),
    NOMBRE VARCHAR(20) NOT NULL,
    CALLE VARCHAR(30),
    NUMERO INT(3),
    PUERTA VARCHAR(2),
    CP INT(5),
    PAIS VARCHAR(10),
    TELEFONO INT(9),
    FAX INT(9),
    CIF VARCHAR(9)    
    );

CREATE TABLE RELACION_MARCA_PROVEEDOR(
    ID_PROVEEDOR INT(100),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    MARCA VARCHAR(10) NOT NULL,
    PRIMARY KEY (MARCA)
);
CREATE TABLE GAFAS(
     ID_PROVEEDOR INT(100),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    MARCA VARCHAR(20),
    GRADUACION_DERECHA INT(2),
    GRADUACION_IZQUIERDA INT(2),
    TIPO_DE_MONTURA VARCHAR(10),
    COLOR_MONTURA VARCHAR(10),
    COLOR_VIDRIOS VARCHAR(10),
    PRECIO INT(3)
);
CREATE TABLE CLIENTES (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_CLIENTE),
    NOMBRE VARCHAR(10),
    CP INT(5),
    TELEFONO INT(9),
    MAIL VARCHAR(20),
    FECHA_REGISTRO DATE,
    RECOMENDADO_POR INT(100) NULL,
    FOREIGN KEY (RECOMENDADO_POR) REFERENCES CLIENTES (ID_CLIENTE) 
    );
CREATE TABLE VENTAS(
    TRABAJADOR VARCHAR(10),
    FECHA_VENTA TIMESTAMP(6),
    ID_CLIENTE INT (10) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);
INSERT INTO PROVEEDOR (NOMBRE,CALLE,NUMERO,PUERTA,CP,PAIS,TELEFONO,FAX,CIF)
VALUES ('CHINO','SINYUN','1','A','43720','CHINA','977777777','977777772', 'B55503678');
INSERT INTO PROVEEDOR (NOMBRE,CALLE,NUMERO,PUERTA,CP,PAIS,TELEFONO,FAX,CIF)
VALUES ('PORTUGUES','OPORTO','2','B','43721','PORTUGAL','977777778','977777773', 'B55503679');
INSERT INTO PROVEEDOR (NOMBRE,CALLE,NUMERO,PUERTA,CP,PAIS,TELEFONO,FAX,CIF)
VALUES ('FRANCES','BEACOUP','3','C','43722','FRANCIA','977777779','977777774', 'B55503679');
INSERT INTO PROVEEDOR (NOMBRE,CALLE,NUMERO,PUERTA,CP,PAIS,TELEFONO,FAX,CIF)
VALUES ('ESPAÑOL','ROCBORONAT','4','D','43723','ESPAÑA','977777770','977777775', 'B55503670');
INSERT INTO RELACION_MARCA_PROVEEDOR (ID_PROVEEDOR,MARCA)
VALUES ('1','TOUS');
INSERT INTO RELACION_MARCA_PROVEEDOR (ID_PROVEEDOR,MARCA)
VALUES ('2','OACKLEY');
INSERT INTO RELACION_MARCA_PROVEEDOR (ID_PROVEEDOR,MARCA)
VALUES ('3','RAYBAN');
INSERT INTO RELACION_MARCA_PROVEEDOR (ID_PROVEEDOR,MARCA)
VALUES ('4','RALPH');
INSERT INTO RELACION_MARCA_PROVEEDOR (ID_PROVEEDOR,MARCA)
VALUES ('1','RALPHK');
INSERT INTO GAFAS (ID_PROVEEDOR,MARCA,GRADUACION_DERECHA, GRADUACION_IZQUIERDA,TIPO_DE_MONTURA,COLOR_MONTURA,COLOR_VIDRIOS,PRECIO)
VALUES ('1','TOUS','2','2','PASTA','NEGRA','BLANCO','100');
INSERT INTO GAFAS (ID_PROVEEDOR,MARCA,GRADUACION_DERECHA, GRADUACION_IZQUIERDA,TIPO_DE_MONTURA,COLOR_MONTURA,COLOR_VIDRIOS,PRECIO)
VALUES ('2','OACKLEY','2','2','PASTA','NEGRA','BLANCO','100');
INSERT INTO GAFAS (ID_PROVEEDOR,MARCA,GRADUACION_DERECHA, GRADUACION_IZQUIERDA,TIPO_DE_MONTURA,COLOR_MONTURA,COLOR_VIDRIOS,PRECIO)
VALUES ('3','RAYBAN','2','2','PASTA','NEGRA','BLANCO','100');
INSERT INTO GAFAS (ID_PROVEEDOR,MARCA,GRADUACION_DERECHA, GRADUACION_IZQUIERDA,TIPO_DE_MONTURA,COLOR_MONTURA,COLOR_VIDRIOS,PRECIO)
VALUES ('4','RALPH','2','2','PASTA','NEGRA','BLANCO','100');
INSERT INTO CLIENTES (NOMBRE,CP,TELEFONO,MAIL,FECHA_REGISTRO,RECOMENDADO_POR)
VALUES ('JUAN','43700','977777777','MAIL','01-01-22','1');
INSERT INTO CLIENTES (NOMBRE,CP,TELEFONO,MAIL,FECHA_REGISTRO,RECOMENDADO_POR)
VALUES ('JUANA','43700','977777777','MAIL','01-01-22','1');
INSERT INTO CLIENTES (NOMBRE,CP,TELEFONO,MAIL,FECHA_REGISTRO)
VALUES ('JUANITO','43700','977777777','MAIL','01-01-22');
INSERT INTO CLIENTES (NOMBRE,CP,TELEFONO,MAIL,FECHA_REGISTRO,RECOMENDADO_POR)
VALUES ('JUANITO','43700','977777777','MAIL','01-01-22','2');
INSERT INTO VENTAS (TRABAJADOR,FECHA_VENTA,ID_CLIENTE)
VALUES ('PEP','01-01-22','1');
INSERT INTO VENTAS (TRABAJADOR,FECHA_VENTA,ID_CLIENTE)
VALUES ('PEP','01-01-22','2');
INSERT INTO VENTAS (TRABAJADOR,FECHA_VENTA,ID_CLIENTE)
VALUES ('LOL','01-01-22','1');
INSERT INTO VENTAS (TRABAJADOR,FECHA_VENTA,ID_CLIENTE)
VALUES ('LOLA','01-01-22','3');
SELECT ID_CLIENTE=1 FROM VENTAS;
