DROP DATABASE IF EXISTS veronicasyoutube;
CREATE DATABASE veronicasyoutube;
USE veronicasyoutube;
CREATE TABLE USUARI(
    ID_USUARI INT (100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_USUARI),
    EMAIL VARCHAR(30),
    PASWORD VARCHAR(10),
    NOM_USUARI VARCHAR (10),
    DATA_NAIXEMENT DATE,
    SEXE VARCHAR (10),
    PAIS VARCHAR (10),
    CP INT (5),
    SUBSCRIPCIONS VARCHAR(100)
);

CREATE TABLE ESTAT(
    ID_ESTAT INT(50) NOT NULL,
    PRIMARY KEY (ID_ESTAT),
    NOM VARCHAR(20)
);
CREATE TABLE CANAL(
    ID_USUARI INT(100) NOT NULL,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    ID_CANAL INT (50) NOT NULL,
    PRIMARY KEY (ID_CANAL),
    NOM VARCHAR(20),
    DESCRIPCIO VARCHAR (50),
    DATA_CREACIO DATE
);
CREATE TABLE ETIQUETA(
    ID_ETIQUETA INT NOT NULL,
    PRIMARY KEY (ID_ETIQUETA),
    NOM_ETIQUETA VARCHAR (10),
    ID_USUARI INT(100) NOT NULL,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    ID_ESTAT INT,
    FOREIGN KEY (ID_ESTAT) REFERENCES ESTAT (ID_ESTAT)
);
CREATE TABLE VIDEOS (
    ID_VIDEO INT(100) NOT NULL ,
    PRIMARY KEY (ID_VIDEO),
    TITOL VARCHAR (20),
    DESCRIPCIO VARCHAR(100),
    GRANDARIA INT (100),
    NOM_ARXIU VARCHAR(20),
    DURADA TIME,
    NUMERO_LIKES INT (100),
    NUMERO_DISLIKES INT (100),
    THUMBNAIL LONGBLOB NULL,
    NUMERO_REPRODUCCIONS INT (100),
    ID_ETIQUETA INT,
    FOREIGN KEY (ID_ETIQUETA) REFERENCES ETIQUETA (ID_ETIQUETA),
    ID_USUARI INT(100) NOT NULL,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    HORA_PUBLICACIO TIME,  
    ID_ESTAT INT,
    FOREIGN KEY (ID_ESTAT) REFERENCES ESTAT (ID_ESTAT)
  
);


CREATE TABLE LIKES_DISLIKES(
    ID_USUARI INT(100) NOT NULL UNIQUE ,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    ID_VIDEO INT (100) NOT NULL,
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEOS (ID_VIDEO),
    DIA_Y_HORA DATETIME,
    TIPO ENUM('LIKE','DISLIKE')
);

CREATE TABLE SUBSCRIPCIONS(
    ID_SUBSCRIPCIO INT NOT NULL,
    PRIMARY KEY (ID_SUBSCRIPCIO),
    ID_USUARI INT,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    ID_ESTAT INT,
    FOREIGN KEY (ID_ESTAT) REFERENCES ESTAT (ID_ESTAT),
    ID_VIDEO INT,
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEOS (ID_VIDEO),
    ID_CANAL INT,
    FOREIGN KEY (ID_CANAL) REFERENCES CANAL (ID_CANAL)
);
CREATE TABLE COMENTARI(
    ID_COMENTARI INT (50) NOT NULL,
    PRIMARY KEY (ID_COMENTARI),
    TEST VARCHAR(50),
    DATA_HORA DATETIME,
    ID_VIDEO INT (100) NOT NULL,
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEOS (ID_VIDEO),
    ID_USUARI INT(100) NOT NULL,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI)
);
CREATE TABLE PLAYLIST(
    ID_USUARI INT(100) NOT NULL,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    ID_VIDEO INT (100) NOT NULL,
    FOREIGN KEY (ID_VIDEO) REFERENCES VIDEOS (ID_VIDEO),
    ESTAT VARCHAR(10) NOT NULL,
    ID_COMENTARI INT,
    FOREIGN KEY (ID_COMENTARI) REFERENCES COMENTARI (ID_COMENTARI),
    ID_LIKE INT NOT NULL,
    NOM_PLAYLIST VARCHAR(20),
    DATA_CREACIO DATE
);
CREATE TABLE COMENTARI_LIKE(
    ID_COMENTARI INT,
    FOREIGN KEY (ID_COMENTARI) REFERENCES COMENTARI (ID_COMENTARI),
    ID_USUARI INT(100) NOT NULL,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    DATA_HORA DATETIME,
    ID_COMENTARI_LIKE INT (50) NOT NULL,
    PRIMARY KEY (ID_COMENTARI_LIKE)
);
CREATE TABLE COMENTARI_DISLIKE(
    ID_COMENTARI INT,
    FOREIGN KEY (ID_COMENTARI) REFERENCES COMENTARI (ID_COMENTARI),
    ID_USUARI INT(100) NOT NULL,
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI (ID_USUARI),
    DATA_HORA DATETIME,
    ID_COMENTARI_DISLIKE INT (50) NOT NULL,
    PRIMARY KEY (ID_COMENTARI_DISLIKE)
);