DROP PROCEDURE IF EXISTS veronicasoptica;
CREATE DATABASE veronicasoptica;
USE veronicasoptica;
CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR INT(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_PROVEEDOR),
    NOMBRE VARCHAR(20) NOT NULL,
    CALLE VARCHAR(30),
    NUMERO INT(3),
    PUERTA VARCHAR(2),
    CP INT(5),
    PAIS VARCHAR(10),
    TELEFONO INT(9),
    FAX INT(9),
    CIF VARCHAR(9)
    );

CREATE TABLE COMPRAS(
    ID_PROVEEDOR INT(100) NOT NULL AUTO_INCREMENT,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    MARCA VARCHAR(20)
);
SELECT MARCA,
IF(MARCA IS NOT NULL, THEN  ) AS RESULT
FROM COMPRAS


CREATE TABLE GAFAS(
    MARCA VARCHAR(20),
    GRADUACION_DERECHA DECIMAL(2,2),
    GRADUACION_IZQUIERDA DECIMAL(2,2),
    TIPO_DE_MONTURA VARCHAR(10),
    COLOR_MONTURA VARCHAR(10),
    COLOR_VIDRIOS VARCHAR(10),
    PRECIO DECIMAL(3,2)
);
CREATE TABLE CLIENTES (
    ID_CLIENTE INT(100) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_CLIENTE),
    NOMBRE VARCHAR(10),
    CP INT(5),
    TELEFONO INT(9),
    MAIL VARCHAR(20),
    FECHA_REGISTRO TIMESTAMP(6),
    RECOMENDADO_POR INT(100),
    FOREIGN KEY (RECOMENDADO_POR) REFERENCES CLIENTES (ID_CLIENTE) 
    );
CREATE TABLE VENTAS(
    TRABAJADOR VARCHAR(10),
    FECHA_VENTA TIMESTAMP(6),
    ID_CLIENTE INT(100) NOT NULL AUTO_INCREMENT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

