DROP DATABASE IF EXISTS veronicaspizzerie;
CREATE DATABASE veronicaspizzerie;
USE veronicaspizzerie;
CREATE TABLE CLIENT(
    ID_CLIENT INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(ID_CLIENT),
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(20),
    CP INT(5),
    TELEFONO INT(9)
);
CREATE TABLE LOCALITAT(
    ID_LOCALITAT INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_LOCALITAT),
    NOM VARCHAR(10),
    ID_CLIENT INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID_CLIENT)
);
CREATE TABLE PROVINCIA(
    ID_PROVINCIA INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_PROVINCIA),
    NOM VARCHAR(10),
    ID_CLIENT INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID_CLIENT)
);
CREATE TABLE COMANDA(
    ID_COMANDA INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_COMANDA),
    FECHA_Y_HORA DATETIME,
    ENTREGA_O_RECOGER VARCHAR(15),
    CANTIDAD_PRODUCTOS INT(20),
    PRECIO_TOTAL INT (100),
    ID_CLIENT INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT (ID_CLIENT)
);
CREATE TABLE PRODUCTOS(
    PIZZAS VARCHAR(10),
    HAMBURGUESAS VARCHAR(10),
    BEBIDAS VARCHAR(10)
   );





CREATE TABLE PIZZAS(
    ID_PIZZA VARCHAR(20),
    PRIMARY KEY(ID_PIZZA),
    NOM VARCHAR(10),
    DESCRIPCIO VARCHAR(50),
    IMATGE ,
    PREU INT(3)
);
CREATE TABLE HAMBURGUESAS(
    ID_HAMBURGUESA VARCHAR(20),
    PRIMARY KEY(ID_HAMBURGUESA),
    NOM VARCHAR(10),
    DESCRIPCIO VARCHAR(50),
    IMATGE ,
    PREU INT(3)
);
CREATE TABLE BEBIDAS(
    ID_BEBIDA VARCHAR(20),
    PRIMARY KEY(ID_BEBIDA),
    NOM VARCHAR(10),
    DESCRIPCIO VARCHAR(50),
    IMATGE ,
    PREU INT(3)
);
CREATE TABLE BOTIGA(
    ID_EMPLEAT INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(ID_EMPLEAT),
    ADREÇA VARCHAR(20),
    CP INT(5),
    ID_LOCALITAT INT (10),
    FOREIGN KEY (ID_LOCALITAT) REFERENCES LOCALITAT (ID_LOCALITAT),
    ID_PROVINCIA INT (10),
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA)
)