

DROP DATABASE IF EXISTS tienda;
CREATE DATABASE tienda CHARACTER SET utf8mb4;
USE tienda;

CREATE TABLE fabricante (
  codigo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

CREATE TABLE producto (
  codigo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  precio DOUBLE NOT NULL,
  codigo_fabricante INT UNSIGNED NOT NULL,
  FOREIGN KEY (codigo_fabricante) REFERENCES fabricante(codigo)
);

INSERT INTO fabricante VALUES(1, 'Asus');
INSERT INTO fabricante VALUES(2, 'Lenovo');
INSERT INTO fabricante VALUES(3, 'Hewlett-Packard');
INSERT INTO fabricante VALUES(4, 'Samsung');
INSERT INTO fabricante VALUES(5, 'Seagate');
INSERT INTO fabricante VALUES(6, 'Crucial');
INSERT INTO fabricante VALUES(7, 'Gigabyte');
INSERT INTO fabricante VALUES(8, 'Huawei');
INSERT INTO fabricante VALUES(9, 'Xiaomi');

INSERT INTO producto VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO producto VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO producto VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO producto VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO producto VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO producto VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO producto VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO producto VALUES(8, 'Portátil Yoga 520', 559, 2);
INSERT INTO producto VALUES(9, 'Portátil Ideapd 320', 444, 2);
INSERT INTO producto VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO producto VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);

SELECT NOMBRE FROM PRODUCTO;
SELECT NOMBRE,PRECIO FROM PRODUCTO;
SELECT * FROM PRODUCTO;
SELECT NOMBRE,PRECIO,PRECIO * 1.07 FROM PRODUCTO;
SELECT  PRODUCTO.NOMBRE AS NOM_DE_PRODUCTO, PRODUCTO.PRECIO AS EUROS, PRODUCTO.PRECIO*1.07 AS DOLARES FROM PRODUCTO;
SELECT UPPER(NOMBRE),PRECIO FROM PRODUCTO;
SELECT LOWER(NOMBRE),PRECIO FROM PRODUCTO;
SELECT NOMBRE, UPPER(LEFT(NOMBRE,2)) FROM FABRICANTE; 
SELECT ROUND(PRECIO) FROM PRODUCTO;
SELECT TRUNCATE(PRECIO,0) FROM PRODUCTO AS TRUNCATED; 
SELECT * FROM FABRICANTE INNER JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE ;
SELECT  *  FROM FABRICANTE  INNER JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE ;
SELECT  FABRICANTE.CODIGO  FROM FABRICANTE  INNER JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE ;
SELECT  DISTINCT FABRICANTE.CODIGO  FROM FABRICANTE  INNER JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE ;
SELECT NOMBRE FROM FABRICANTE ORDER BY FABRICANTE.NOMBRE ASC;
SELECT NOMBRE FROM FABRICANTE ORDER BY FABRICANTE.NOMBRE DESC;
SELECT NOMBRE,PRECIO FROM PRODUCTO ORDER BY NOMBRE ASC, PRECIO DESC;
SELECT * FROM FABRICANTE LIMIT 5;
SELECT * FROM FABRICANTE LIMIT 2 OFFSET 3;
SELECT NOMBRE,PRECIO FROM PRODUCTO ORDER BY PRECIO ASC LIMIT 1;
SELECT NOMBRE,PRECIO FROM PRODUCTO ORDER BY PRECIO DESC LIMIT 1;
SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE CODIGO_FABRICANTE=2;
SELECT PRODUCTO.NOMBRE,PRODUCTO.PRECIO,FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.CODIGO_FABRICANTE=FABRICANTE.CODIGO;
SELECT PRODUCTO.NOMBRE,PRODUCTO.PRECIO,FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.CODIGO_FABRICANTE=FABRICANTE.CODIGO ORDER BY FABRICANTE.NOMBRE ASC;
SELECT PRODUCTO.CODIGO_FABRICANTE,PRODUCTO.NOMBRE,FABRICANTE.CODIGO,FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON PRODUCTO.CODIGO_FABRICANTE=FABRICANTE.CODIGO;
SELECT PRODUCTO.NOMBRE,PRODUCTO.PRECIO,FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE WHERE PRODUCTO.CODIGO_FABRICANTE=FABRICANTE.CODIGO ORDER BY PRODUCTO.PRECIO ASC LIMIT 1;
SELECT PRODUCTO.NOMBRE,PRODUCTO.PRECIO,FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE WHERE PRODUCTO.CODIGO_FABRICANTE=FABRICANTE.CODIGO ORDER BY PRODUCTO.PRECIO DESC LIMIT 1;
SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE='LENOVO';
SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE='CRUCIAL' AND PRODUCTO.PRECIO>=200 ;
SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE='ASUS'OR FABRICANTE.NOMBRE ='Hewlett-Packard' OR FABRICANTE.NOMBRE ='SEAGATE'  ;
SELECT PRODUCTO.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE IN ('ASUS','Hewlett-Packard','SEAGATE');
SELECT PRODUCTO.NOMBRE,PRODUCTO.PRECIO FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE LIKE '%E'; 
SELECT PRODUCTO.NOMBRE,PRODUCTO.PRECIO FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE LIKE '%W%'; 
SELECT PRODUCTO.NOMBRE,PRODUCTO.PRECIO,FABRICANTE.NOMBRE FROM PRODUCTO INNER JOIN FABRICANTE ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE WHERE PRODUCTO.PRECIO>=180 ORDER BY PRODUCTO.PRECIO DESC, FABRICANTE.NOMBRE ASC;
SELECT FABRICANTE.CODIGO,FABRICANTE.NOMBRE FROM FABRICANTE INNER JOIN PRODUCTO ON FABRICANTE.CODIGO=PRODUCTO.CODIGO_FABRICANTE;
SELECT * FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE;
SELECT * FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE WHERE PRODUCTO.NOMBRE IS NULL;
SELECT * FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE='Lenovo';
SELECT * FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE WHERE PRODUCTO.PRECIO>=559 ORDER BY PRODUCTO.PRECIO DESC;
SELECT * FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE='Lenovo' ORDER BY PRODUCTO.PRECIO DESC LIMIT 1;
SELECT * FROM FABRICANTE LEFT JOIN PRODUCTO ON FABRICANTE.CODIGO = PRODUCTO.CODIGO_FABRICANTE WHERE FABRICANTE.NOMBRE='Hewlett-Packard' ORDER BY PRODUCTO.PRECIO ASC LIMIT 1;






